-- Referencia: la DB ya la crea Docker Compose.
-- Conexión: localhost:5433 / db=jeb / user=jeb / password=jeb
--
-- El esquema lo genera JPA al desplegar la app.
-- Usa este script solo si quieres crear la tabla a mano.

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    price NUMERIC(10, 2) NOT NULL,
    stock INT NOT NULL
);
